version: '3'
services:
  mysql:
    image: centos/mysql-56-centos7:latest
    environment:
      - MYSQL_USER=
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=wordpress
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - mail
    hostname: mysql
    container_name: mysql

  php-fpm:
    build:
      dockerfile: Dockerfile
      context: ./php
    networks: 
      - mail
    volumes:
      - www:/var/www
    hostname: php-fpm
    container_name: php-fpm

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    networks: 
      - mail
    ports:
      - "18080:80"
      - "18443:443"
    volumes:
      - www:/var/www
    depends_on: 
      - php-fpm
      - ssl
    hostname: nginx
    container_name: nginx

  opendkim:
    image: instrumentisto/opendkim:2.10.3-alpine
    volumes:
      - opendkim:/etc/opendkim\
    networks:
      - mail
    hostname: opendkim
    container_name: mailserver_opendkim


volumes:
  www:
  mysql_db:
  opendkim:

networks:
  mail:
