version: '3'
services:
  mysql:
    env_file:
      - .env
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - mail
    ports:
      - "6033:3306"
    hostname: mysql
    container_name: mysql

  php-fpm:
    build:
      dockerfile: Dockerfile
      context: ./php
    networks: 
      - mail
    volumes:
      - www:/var/www
    hostname: php-fpm
    container_name: php-fpm

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    networks: 
      - mail
    ports:
      - "18080:80"
      - "18443:443"
    volumes:
      - www:/var/www
    depends_on: 
      - php-fpm
#      - ssl
    hostname: nginx
    container_name: nginx

  roundcube:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    networks:
      - mail
    volumes:
      - www:/var/www
    hostname: roundcube
    container_name: roundcube


volumes:
  www:
  mysql_db:

networks:
  mail:
